print('*** Welcome to the Email Generator System ***')
name = input('What is your name?: ')
surename = input('What is your surename?: ')
name_lo = name.lower()
surename_lo = surename.lower()

print(f'''Your new email generated by the system is:
      {name_lo}.{surename_lo}@gothamcity.com
''')